version: '3.8'

services:
  apipy:
    build:
      context: ./apipy
    ports:
    - 8004:8000
    volumes:
    - ./apipy:/app/src
    networks:
      - quizznetwork
    command: uvicorn apipy.main:app --reload --host 0.0.0.0 --port 8000
  frontend:
    build:
      context: ./frontend
    ports:
    - 8104:3000
    volumes:
    - /app/node_modules
    - ./frontend:/app/src
    networks:
      - quizznetwork
    command: bash -c "cd quizzos && npm start"
  apirust:
    build:
      context: ./apirust
    ports:
    - 8005:8000
    volumes:
    - ./apirust:/app/src
    networks:
      - quizznetwork
    command: "sleep 5000" #bash -c "cd apirust && cargo run"

networks:
  quizznetwork:
    name: quizz_network