version: '3.8'

services:
  apipy:
    build:
      context: ./apipy
    ports:
    - 8004:8000
    volumes:
    - ./apipy:/app/src
    command: uvicorn apipy.main:app --reload --host 0.0.0.0 --port 8000